-- Catalog
CREATE SCHEMA IF NOT EXISTS catalog AUTHORIZATION bgstore;

-- Cart
CREATE SCHEMA IF NOT EXISTS cart AUTHORIZATION bgstore;

-- Order
CREATE SCHEMA IF NOT EXISTS orders AUTHORIZATION bgstore;

-- Authentication
CREATE SCHEMA IF NOT EXISTS authentication AUTHORIZATION bgstore;

-- Users
CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION bgstore;
CREATE TABLE users.user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             VARCHAR(255),
    password             VARCHAR(255),
    first_name           VARCHAR(255),
    middle_name          VARCHAR(255),
    last_name            VARCHAR(255),
    email                VARCHAR(255),
    mobile_phone         VARCHAR(255),
    thumbnail_id         VARCHAR(255),
    photo_id             VARCHAR(255),
    birth_date           DATE,
    need_change_password BOOLEAN,
    CONSTRAINT pk_user PRIMARY KEY (id)
);


-- Shipping
CREATE SCHEMA IF NOT EXISTS shipping AUTHORIZATION bgstore;

-- Payment
CREATE SCHEMA IF NOT EXISTS payment AUTHORIZATION bgstore;
