version: '3.9'

services:

  bgstore-postgres:
    image: postgres:14.5
    hostname: bgstore-postgres
    container_name: bgstore-postgres
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: bgstoredb
      POSTGRES_USER: bgstore
      POSTGRES_PASSWORD: bgpass
    ports:
      - "5432:5432"